backend:
  name: git-gateway
  repo: Asifsaheer/Asif-Saheer-Kv-portfolio-
  branch: main
  identity_url: https://auth.decapbridge.com/sites/https://asifsaheerkv.netlify.app/
  gateway_url: https://gateway.decapbridge.com
